stages:  
  - deploy-service
  - build-static-site  
  - deploy-static-site
  
deploy-service:
  stage: deploy-service
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
  before_script:
    - docker info
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_REGISTRY: "cntrdataanda.azurecr.io"
    DOCKER_USERNAME: "cntrdataanda"
    MODEL: "datasets-collector-service"
    VERSION: "0.3.1"
  script:
    - docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_REGISTRY/$MODEL:$VERSION .
    - docker push $DOCKER_REGISTRY/$MODEL:$VERSION

build-static-site:
  image: node:15.12-alpine3.13
  stage: build-static-site
  variables:
    BASE_URL: "/"
  artifacts:
    paths:
    - userinterface/dist
  script:
    - cd userinterface
    - npm install
    - DATASHARING_DOMAIN="https://stacwebdatasetssharing.z8.web.core.windows.net"  DATAROUTING_DOMAIN=https://stacwebdatasetsrouting.z8.web.core.windows.net APPFRAME_DOMAIN="https://stacwebappframe.z8.web.core.windows.net" STYLE_DOMAIN="https://stacwebstyle.z8.web.core.windows.net" npm run build

deploy-static-site:
  image: mcr.microsoft.com/azure-cli
  stage: deploy-static-site
  needs: [build-static-site]
  variables:
    BASE_URL: "/"
  artifacts:
    paths:
    - userinterface/dist/  
  script:
    - az storage blob delete-batch -s "\$web" --connection-string $AZURE_STORAGE_CONNECTION_STRING
    - az storage blob upload-batch -d "\$web" -s userinterface/dist --connection-string $AZURE_STORAGE_CONNECTION_STRING  
